/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1e5e3a",
        "on-error-container": "#93000a",
        "inverse-primary": "#94d5a7",
        "surface": "#f9f9f7",
        "secondary-fixed-dim": "#c8c7bf",
        "surface-variant": "#e2e3e1",
        "on-tertiary-fixed-variant": "#464744",
        "on-primary-container": "#94d5a8",
        "on-background": "#1a1c1b",
        "on-tertiary-container": "#c6c7c2",
        "on-secondary-fixed": "#1b1c17",
        "on-surface-variant": "#404941",
        "outline-variant": "#c0c9bf",
        "on-primary-fixed-variant": "#0d512f",
        "error": "#ba1a1a",
        "primary-fixed": "#aff2c2",
        "surface-container-highest": "#e2e3e1",
        "on-primary-fixed": "#00210f",
        "secondary-container": "#e4e3da",
        "secondary-fixed": "#e4e3da",
        "on-secondary-container": "#64655e",
        "surface-bright": "#f9f9f7",
        "on-surface": "#1a1c1b",
        "on-secondary-fixed-variant": "#474741",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c7c2",
        "on-error": "#ffffff",
        "tertiary": "#3a3c39",
        "surface-container-high": "#e8e8e6",
        "tertiary-fixed": "#e3e3de",
        "surface-dim": "#dadad8",
        "surface-container": "#eeeeec",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9f7",
        "surface-container-low": "#f4f4f2",
        "secondary": "#5e5f58",
        "outline": "#707971",
        "inverse-surface": "#2f3130",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-container": "#525350",
        "on-primary": "#ffffff",
        "surface-tint": "#2b6a45",
        "primary-fixed-dim": "#94d5a7",
        "primary": "#004625",
        "on-tertiary-fixed": "#1a1c19",
        "warm-milk": "#F7F5F0"
      },
      borderRadius: {
        "DEFAULT": "6px", // matching 6px from Design Brief
        "lg": "6px",
        "xl": "12px",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "stack-sm": "8px",
        "container-padding": "var(--container-padding)",
        "gutter": "16px",
        "stack-md": "16px",
        "stack-lg": "24px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "300" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "300" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
